# Generated by Django 4.2.3 on 2023-07-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='data_of_death',
            new_name='date_of_death',
        ),
    ]
