# Generated by Django 4.2.3 on 2023-07-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_mark_late', 'Set book as late'), ('can_renew', 'Set new due_back date'))},
        ),
    ]
